Fus 520 automate splitting of large po
SportPursuit/wms pull request #60
Opened 2021-11-12 14:56 UTC by tadesanya

Ticket: https://sportpursuit.atlassian.net/browse/FUS-520

2021-11-15 16:07 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +            split_line_nodes = [orig_line_node[i:i + PO_FILE_LINE_SIZE_THRESHOLD] for i in range(0, len(orig_line_node), PO_FILE_LINE_SIZE_THRESHOLD)]
Can you explain what adverse effects a one liner code has on the system, and how it might cause errors?

2021-11-15 16:09 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +            split_line_nodes = [orig_line_node[i:i + PO_FILE_LINE_SIZE_THRESHOLD] for i in range(0, len(orig_line_node), PO_FILE_LINE_SIZE_THRESHOLD)]
Can you explain how a one liner code can have adverse effects on the system or errors it might produce?

2021-11-15 16:30 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +            split_line_nodes = [orig_line_node[i:i + PO_FILE_LINE_SIZE_THRESHOLD] for i in range(0, len(orig_line_node), PO_FILE_LINE_SIZE_THRESHOLD)]
I didn't say that it would cause errors, I said it was complicated and would be clearer if extracted to its own method

2021-11-16 14:12 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +    def split_large_po_file(self, file_contents):
done

2021-11-16 14:13 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +            split_line_nodes = [orig_line_node[i:i + PO_FILE_LINE_SIZE_THRESHOLD] for i in range(0, len(orig_line_node), PO_FILE_LINE_SIZE_THRESHOLD)]
done

2021-11-16 14:14 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +        po_ids = purchase_obj.search(cr, uid, [('name', '=', po_name), ('bots_cross_dock', '=', False)])
done

2021-11-16 14:15 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +            orig_line_node = file_contents[0]['orderconf']['shipment'][0].pop('line')
I've added a check for the picking_conf file type to make sure only files of type `in` are split. So the we won't have an issue with multiple shipment nodes that occur in a delivery order picking_conf

2021-11-16 14:51 UTC, scrampin requested changes

2021-11-16 14:51 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +    def _split_line_node_into_chunks(self, line_node):
This method doesn't remove the complexity of the line that executes the splitting. If you search the Odoo codebase for a method called `chunks` you'll find a method that you can copy to here that can be used instead (you'll probably want to rename your `chunks` var below as well)

2021-11-16 14:51 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +            return True
This would be simpler if you defined a variable such as `split_file = False` at the beginning of the method, redefined it to true under the conditions that would warrant the file to be split (i.e. the file type being 'in' and the PO not being crossdock), and then return split_file at the end

2021-11-16 14:51 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +        po_type = file_contents[0]['orderconf']['shipment'][0]['type']
This is not the type of the PO, this is the type of the file

2021-11-16 14:53 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +            split_line_nodes = [orig_line_node[i:i + PO_FILE_LINE_SIZE_THRESHOLD] for i in range(0, len(orig_line_node), PO_FILE_LINE_SIZE_THRESHOLD)]
I've got a similar concern about the new method, as you've not broken down this single liner at all as part of it, but I've raised in another comment

2021-11-16 15:16 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +    def _split_line_node_into_chunks(self, line_node):
There is a very similar list comprehension for creating a chunk in connector_bots_stock_integration/supplier_stock.py line 119

2021-11-16 15:50 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +    def _split_line_node_into_chunks(self, line_node):
Ok, I don't think that makes my suggestion any less relevant though?

2021-11-17 15:36 UTC, tadesanya commented
@scrampin the latest push addresses all of your concerns

2021-11-17 15:43 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +            return True
This method can be tidied up in the following ways:
1. returning false at the beginning of the method if the file type is 'out'. In that case it's a waste of resources to look up a PO since you already have enough info to determine the splitting shouldn't happen
2. Implementing the above suggestion about defining and returning true/false

2021-11-17 15:44 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +    def _split_line_node_into_chunks(self, line_node):
If you pass the splitting threshold as an argument into this method, you can then use that argument instead of the static var.

2021-11-17 15:46 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +        logger.info("Splitting PO FIle.")
'i' in FIle should be lower case

2021-11-17 15:47 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +                    logger.info("Chunk of Picking File content: {}".format(file_contents))
Are you planning to get rid of these extra logs before shipping?

2021-11-17 15:48 UTC, scrampin reviewed
Looks good for the most part, just a couple of things to tidy up

2021-11-17 16:24 UTC, tadesanya commented on connector_bots/stock_warehouse.py
> +                    logger.info("Chunk of Picking File content: {}".format(file_contents))
Yes

2021-11-17 16:24 UTC, tadesanya commented
@scrampin code refactored

2021-11-17 16:33 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +        if picking_shipment_type == 'out':
You can just check `if picking_shipment_type != 'in'` here

2021-11-17 16:34 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +            if po_ids and picking_shipment_type == 'in':
If you make the change suggested above, you don't need to check for the picking type again here

2021-11-17 16:36 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +                    logger.info("Chunk of Picking File content: {}".format(file_contents))
Cool, thank you. Can you get rid of the logs that you need to to make the code production ready before asking for final review?

2021-11-17 16:45 UTC, tadesanya commented
@scrampin  code refactored

2021-11-17 16:51 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +        if picking_shipment_type != 'out':
This should be 'in' above

2021-11-17 16:51 UTC, scrampin reviewed
One quick typo to change, and a request to remove the extra testing comments

2021-11-17 16:53 UTC, tadesanya commented
refactored, need the logs for QA. Will remove them after QA is done

2021-11-17 16:54 UTC, scrampin commented
I don't think you do need the logs for QA? If you've used the logs to satisfy yourself that the code is doing what it shouldm then what goes through QA should be production ready

2021-11-17 16:57 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +        else:
You actually don't need to use 'else' here, since you return in the case of the above 'if' statement being true. So you can safely get rid of the 'else' and unindent the below code

2021-11-17 17:00 UTC, tadesanya commented
code refactored

2021-11-17 17:04 UTC, scrampin approved these changes

2021-11-18 12:30 UTC, tadesanya commented
@scrampin you might want to go through this again, made some changes to it

2021-11-18 12:37 UTC, scrampin commented
Thanks, I'll take a look this afternoon

2021-11-18 14:07 UTC, scrampin commented on connector_bots/stock_warehouse.py
> +                    picking_conf_template_copy = copy.deepcopy(picking_conf_template)
I think that if you rewrite this as:
`picking_conf_copy = copy.deepcopy(file_contents)`
`picking_conf_copy[0]['orderconf']['shipment'] = [shipment_copy]`

Then you can get rid of lines 503 and 504?

2021-11-19 09:36 UTC, scrampin requested changes
Re-reviewed yesterday just one comment on the re-copying of the file contents to check

2021-11-19 09:45 UTC, tadesanya commented
refactor done

2021-11-19 10:07 UTC, scrampin approved these changes

2021-11-30 14:35 UTC, merged